version: '3.9'

services:
  staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-staging
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: staging
    restart: always

  production:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
